apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate  # Ensure this matches the label from your Terraform script
    spec:
      containers:
        - name: weaviate
          image: 891612581521.dkr.ecr.us-east-1.amazonaws.com/private-ai-deployment-ci-cd/weaviate-custom:latest  # Your ECR image URI
          ports:
            - containerPort: 8080   # HTTP port
            - containerPort: 50051  # gRPC port
          env:
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_DATA_PATH
              value: "/var/lib/weaviate"
            - name: ENABLE_API_BASED_MODULES
              value: "true"
            - name: CLUSTER_HOSTNAME
              value: "node1"
          livenessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      nodeSelector:
        app: weaviate  # Ensures the pod is scheduled on nodes with the 'app=weaviate' label
