apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: __FILE_SYSTEM_ID__
  accessPointId:  __ACCESS_POINT_ID__
  directoryPerms: "700"
reclaimPolicy: Retain
volumeBindingMode: Immediate
