apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: 891612581521.dkr.ecr.us-east-1.amazonaws.com/private-ai-deployment-ci-cd/ollama:latest
          ports:
            - containerPort: 11434
          resources:
            limits:
              nvidia.com/gpu: 1
              ephemeral-storage: "20Gi"     # <-- Add this
            requests:
              nvidia.com/gpu: 1
              ephemeral-storage: "15Gi"     # <-- And this
      nodeSelector:
        gpu: "true"  # Use the GPU-enabled node as per the label in your Terraform script
      tolerations:
        - key: "gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"  # Ensure that the pod can be scheduled on the tainted node
